#!/usr/bin/env bash

set -e

if [ ! -f /usr/local/bin/uv ]; then
    echo "==> Installing uv"
    curl -LsSf https://astral.sh/uv/install.sh | sh
fi

echo "==> Creating venv"
uv venv .VENV

echo "==> Activating venv"
source .VENV/bin/activate

echo "==> Installing packages"
uv pip install ipykernel jupyterlab
uv pip install -e .

echo "==> Creating jupyter kernel"
python -m ipykernel install --user --name=.VENV --display-name="Python 3.12 (.VENV)"
